### ISSUE TITLE
Call to a member function parameterNames() on a non-object

### ISSUE THREAD

**Issue by Gummibeer** [Riari/laravel-forum#90] opened 2015-12-10 16:42 UTC
```
FatalErrorException in BaseModel.php line 144: Call to a member function parameterNames() on a non-object
```

I don't know if this is frontend or backend related - but I get this Exception if I have a category and try to call `$category->route`.

Any ideas?

**Comment by Dreaw** [comment] 2015-12-10 21:08
Some problem!

**Comment by Riari** [comment] 2015-12-10 21:09
Which package versions are you using, and can you do a `dd($category)` and show the result here?

The route/URL attributes on the models have been deprecated in the latest release since they're strictly front-end. To take their place, the front-end now has a new `Forum::route()` method to aid in generating URLs, but the model attributes are at least supposed to work still.

**Comment by Dreaw** [comment] 2015-12-10 21:18
"riari/laravel-forum": "~3.0",
"riari/laravel-forum-frontend": "~1.0"

I didn't change anything, I did according to the configuration, and then tried to create category from the default front-end.

**Comment by Riari** [comment] 2015-12-10 21:44
OK, I realise what the problem is now. While working on the routing, I renamed the `forum.category.index` route to `forum.category.show` to make it consistent with everything else, but forgot to update the route attribute on the Category model.

I've just pushed a fix for it - let me know if it works for you: cca7304c61d75f29e50c94a97a093252cd2d10f1

Note that this isn't a problem with the latest front-end views, so if you don't want to wait for a new release with the fix, just change your `$category->route` to `Forum::route('category.show', $category)`. (Or if you aren't overriding the category.index view, just do a `composer update` to get the latest ones from the package)

**Comment by Dreaw** [comment] 2015-12-10 21:56
Now it's Okay. Thank's Riari.

**Comment by Riari** [comment] 2015-12-10 22:10
No problem!

**Closed as completed by Riari** 2015-12-10 22:10 UTC
Labels: type: bug

**Comment by Gummibeer** [comment] 2015-12-10 22:39
Ok, thx for the info with the `Forum::route('category.show', $category)` - I will add this to my views.

PS: this fixed the problem. But is anywhere a list of the route names to use for categories, threads and posts?

**Comment by Riari** [comment] 2015-12-10 23:02
Just use `php artisan route:list`. `Forum::route()` will accept route names with or without the preceding 'forum.' part.

More info here: http://teamteatime.net/docs/laravel-forum/3.x/front-end/helpers.md
