### ISSUE TITLE
Category thread/post count doesn't update on thread move

### ISSUE THREAD

**Issue by alexqhj** [Riari/laravel-forum#146] opened 2016-09-09 13:30 UTC
When moving a thread from one category to another, the category `post_count` and `thread_count` do not update.

Here I moved a thread from Category One to Category Two
http://i.imgur.com/VpG81ES.png

As you can see, the count fields were not updated.

**Comment by Riari** [comment] 2016-09-10 20:56
Fixed in [3.1.4](https://github.com/Riari/laravel-forum/releases/tag/3.1.4) - thanks!

Edit: just to note, incorrect category stats caused by this issue can be rectified by running `php artisan forum:refresh-stats`

**Closed as completed by Riari** 2016-09-10 20:56 UTC
Labels: type: bug
