### ISSUE TITLE
Call to a member function isEmpty() on string

### ISSUE THREAD

**Issue by DevHoracioRodriguez** [Riari/laravel-forum#319] opened 2022-10-13 03:20 UTC
Deleting categories from Manage, generates error. Please, for more info visit the following link - https://flareapp.io/share/LPl18nB7#F68

**Comment by DevHoracioRodriguez** [comment] 2022-10-13 03:34
This error goes away with php artisan route:clear and re-appears with php artisan optimize.

**Comment by Riari** [comment] 2022-10-13 08:13
Thanks for reporting this. As far as I can tell from a brief search, this (along with the other issues) is caused by route bindings being inside the route files. They're loaded from within route groups and when they're cached, the bindings no longer take effect.

I'll try to get a new release out with a fix later today.

**Comment by Riari** [comment] 2022-10-13 13:42
I've created release [5.3.4](https://github.com/Team-Tea-Time/laravel-forum/releases/tag/5.3.4) with the fix. I'll close this along with the other issues pertaining to it, but please feel free to follow up on any of them or create a new issue if you encounter recurring problems. Thanks!

**Closed as completed** 2022-10-13 13:42 UTC

**Comment by DevHoracioRodriguez** [comment] 2022-10-13 21:09
Thank you Riari. This fixed the problem.
